export const ALL_PRODUCTS_REQUESTS='ALL_PRODUCTS_REQUESTS'
export const ALL_PRODUCTS_SUCCESS='ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL='ALL_PRODUCTS_FAIL'
export const CLEAR_ERRORS='CLEAR_ERRORS'

export const ALL_PRODUCTS_DETAILS_REQUESTS='ALL_PRODUCTS_REQUESTS'
export const ALL_PRODUCTS_DETAILS_SUCCESS='ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_DETAILS_FAIL='ALL_PRODUCTS_FAIL'



export const NEW_REVIEW_FAIL='NEW_REVIEW_FAIL'

